version: '3.8'

services:
  mcp-gcal-sse:
    image: node:18-alpine
    container_name: g2n-mcp-gcal-sse
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm run build &&
             npm start"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TOKEN_STORAGE_PATH=/app/data/tokens.json
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - gcal_tokens:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  gcal_tokens:
    driver: local

# Opcional para Swarm em produção:
# 
# networks:
#   frontend:
#     external: true
#   backend:
#     external: true
#
# secrets:
#   google_client_id:
#     external: true
#   google_client_secret:
#     external: true 